config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  devise_for :users
  get "/home/about" => "home#about", as: "about"
  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy] 
  resources :users, only: [:index, :show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  
  validates :title, presence: true
  validates :body, presence: true
  validates :body, length: { maximum: 200 }
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_one_attached :profile_image
  
  validates :name, uniqueness: true
  validates :name, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }

  def get_profile_image(width,height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?
  add_flash_types :success, :info, :warning, :danger

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
 before_action :baria_user, only:[:edit, :update]

  def new
   @book = Book.new
  end

  def create
   @book = Book.new(book_params)
   @book.user_id = current_user.id
   if @book.save
    flash[:success] = 'successfully'
    redirect_to book_path(@book.id)
   else
    @books = Book.all
    @user = current_user
    render :index
   end
  end

  def index
   @books = Book.all
   @book = Book.new
   @user = current_user
  end

  def show
   @books = Book.all
   @book= Book.find(params[:id])
   @user = current_user
  end

  def edit
   @book = Book.find(params[:id])
   unless @book.user_id = current_user.id
    redirect_to book_path
   end
  end

  def update
    @book = Book.find(params[:id])
    @book.update(book_params)
   if @book.save
    flash[:success] = 'successfully'
    redirect_to book_path(@book.id)
   else
    @books = Book.all
    @user = current_user
    render :edit
   end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
   params.require(:book).permit(:title, :image, :body)
  end
  
  def baria_user
    if current_user.id != Book.find(params[:id]).user_id
      redirect_to books_path
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def about
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :baria_user, only:[:edit, :update]


  def new

  end

  def index
    @users = User.all
    @user = current_user
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books

  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    if @user.save
      flash[:success] = 'successfully'
      redirect_to user_path
    else
      @user = User.find(params[:id])
      @user.update(user_params)
      render :edit
    end
  end


  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def baria_user
    if current_user.id != params[:id].to_i
      redirect_to user_path(current_user.id)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<h2>User info</h2>
    <%= image_tag user.get_profile_image(100,100) %>
    <table class="table">
        <tbody>
            <tr></tr>
            <tr>
              <th>name</th>
              <td><%= user.name %></td>
            </tr>
            <tr>
              <th>introduction</th>
              <td><%= user.introduction %></td>
            </tr>
        </tbody>
    </table>

    <div class="row">
        <%= link_to edit_user_path(user), class: 'btn btn-outline-secondary btn-block' do %>
            <i class="fas fa-user-cog"></i>
        <% end %>
    </div>

    <h2 class="mt-3">New book</h2>
    <%= form_with model: Book.new do |f| %>
        <div class="form-group">
            <p>Title</p>
            <%= f.text_field :title %>
        </div>

        <div class="form-group">
            <p>Opinion</p>
            <%= f.text_area :body %>
        </div>

        <div class="form-group">
            <%= f.submit 'Create Book', class: "btn btn-success" %>
        </div>
    <% end %>
      

app/views/books/edit.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		  <h1>Editing Book</h1>
    	  <%= form_with model: @book do |f| %>
    	    <% if @book.errors.any? %>
            <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
            <ul>
              <% @book.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          <% end %>
          <div class="form-group">
            <p>Title</p>
            <%= f.text_field :title, class: "form-control book_title" %>
          </div>

          <div class="form-group">
            <p>Opinion</p>
            <%= f.text_area :body, class: "form-control book_body" %>
          </div>

          <div class="form-group">
            <%= f.submit 'Update Book', class: "btn btn-success" %>
          </div>
        <% end %>

  		<%= link_to "Show", book_path(@book.id) %> |
  		<a class="back" href="/books">Back</a>
      </div>
    </div>
  </div>
</main>

app/views/books/index.html.erb
<main>
  <div class="container px-5 px-sm-0">
    <% if @book.errors.any? %>
      <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
        <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
    <% end %>
    <div class="row">
      <div class="col-md-3">
        <%= render 'books/list', user: @user %>
      </div>
      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
        <table class="table">
          <tbody>
            <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
              </tr>
            </thead>
            <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user_id) do %>
                  <%= image_tag book.user.get_profile_image(100,100) %>
                <% end %>
              </td>
              <td>
                <%= link_to book_path(book.id) do %>
                  <%= book.title %>
                <% end %>
              </td>
              <td><%= book.body %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/books/new.html.erb
<h1>画像投稿フォーム</h1>
  <% if @book.errors.any? %>
  <%= @book.errors.count %>件のエラーが発生しました
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
  
<% end %>
  <%= form_with model: @book do |f| %>
    <h4>画像</h4>
      <%= f.file_field :image, accept: "image/*" %>
    <h4>本のタイトル</h4>
      <%= f.text_field :title %>
    <h4>感想</h4>
      <%= f.text_area :body %>
    <%= f.submit '投稿' %>
  <% end %>

app/views/books/show.html.erb
<main>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">
        <%= render 'books/list', user: @book.user %>
      </div>
      <div class="col-md-8 offset-md-1">
        <h2>Book detail</h2>
        <table class="table">
          <tbody>
            <tr>
            <td>
              <%= link_to user_path(@book.user.id) do %>
                <%= image_tag @book.user.get_profile_image(100,100) %><br>
                <%= @book.user.name %>
              <% end %>
            </td>
            <td>
              <%= link_to book_path(@book.id) do %>
               <%= @book.title %>
              <% end %>
            </td>
            <td>
              <%= @book.body %>
            </td>
              <% if @book.user == current_user %>
              <td><%= link_to "Edit", edit_book_path(@book), class: "btn btn-sm btn-success" %></td>
              <td><%= link_to "Destroy", book_path(@book.id), class: "btn btn-sm btn-danger ", method: :delete, "data-confirm" => "Are you sure?" %></td>
              <% end %>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/home/about.html.erb
<div class="container">
    <div class="row">
        <h1 class="px-3 mx-auto">
            Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!
        </h1>
    </div>
</div>

app/views/homes/top.html.erb
<body>
  <main>
    <p id="notice"></p>
    <div class="container">
      <div class="row">
        <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
          <h1>welcome to 
            <i class="fas fa-book"></i><strong>Bookers</strong> 
            !!
          </h1>
          <p>In 
          <i class="fas fa-book"></i><strong>Bookers</strong> ,
          </p>
          <p>
            you can share and exchange your opinions , inpressions , and emotions<br>
          </p>
          <p>about various books!</p>
          <div class="btn-wrapper col-10 mx-auto">
            <div class="row">
              <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
            </div>
            <div class="row">
              <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <a class="brand" href="/">
            <span>Bookers</span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to user_path(current_user.id), class: 'nav-link text-white' do %>
              <i class="fas fa-home"></i> Home
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to users_path, class: 'nav-link text-white' do %>
                <i class="fas fa-users"></i> Users
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to books_path,class: 'nav-link text-white' do %>
                <i class="fas fa-book-open"></i> Books
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-light' do %>
                <i class="fas fa-sign-out-alt"></i> Log out
              <% end %>
            </li>
            <% else %>
            <li>
              <a class="nav-link text-light" href="/">
                <i class="fas fa-home"></i> Home
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-light" href="/home/about" >
                <i class="fas fa-link"></i> About
              </a>
            </li>
            <li class="nav-item">
              <%= link_to new_user_registration_path, class: 'nav-link text-light' do %>
                <i class="fas fa-user-plus"></i> Sign up
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_user_session_path,  class: 'nav-link text-light' do %>
                <i class="fas fa-sign-in-alt"></i> Log in
              <%end %>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main class="mb-auto">
      <% flash.each do |message_type, message| %>
      <%= content_tag :div, message, class: message_type %>
      <% end %>
    <%= yield %>
    </main>

    <footer>
      <div class='container mt-5'>
  	    <div class='row'>
    	    <div class='mx-auto'>
    	      <p>CopyRight Infratop.inc</p>
    	    </div>
        </div>
      </div>
    </footer>

  </body>
</html>

app/views/users/edit.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h2>User info</h2>
        <%= form_with model: @user do |f| %>
          <% if @user.errors.any? %>
            <h3><%= @user.errors.count %> errors prohibited this obj from being saved:</h3>
            <ul>
              <% @user.errors.full_messages.each do |message| %>
                 <li><%= message %></li>
              <% end %>
            </ul>
          <% end %>
          <div class="form-group">
            <label for="inputName">Name</label>
            <%= f.text_field :name, autofocus: true, class: "form-control name", id:"inputName", placeholder:"名前"%>
          </div>
          <div class="form-group">
            <label for="inputImage">Image</label><br>
            <%= f.file_field :profile_image,　class: "form-control-file user_image", placeholder: "ファイルを選択", accept: "image/*" %>
          </div>
          <div class="form-group">
            <label for="user_introduction">Introduction</label>
            <%= f.text_area :introduction, class: "form-control introduction" %>
          </div>
          <div class="form-group">
            <%= f.submit "Update User", class: "btn btn-secondary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</main>

app/views/users/index.html.erb
<main>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">
        <%= render 'books/list', user: @user %>
      </div>
      <div class="col-md-8 offset-md-1">
        <h2>Users</h2>
        <table class="table">
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
            <tr>
              <td><%= image_tag user.get_profile_image(100,100) %></td>
              <td><%= user.name %></td>
              <td>
                <%= link_to "Show", user_path(user.id) %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<main>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">
        <%= render 'books/list', user: @user %>
      </div>
      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
        <table class="table">
          <tbody>
            <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
              </tr>
            </thead>
            <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(@user.id) do %>
                <%= image_tag book.user.get_profile_image(100,100) %>
                <% end %>
              </td>
              <td>
                <%= link_to book_path(book.id) do %>
                  <%= book.title %>
                <% end %>
              </td>
              <td><%= book.body %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>